### ISSUE TITLE
Ineligible Repository

### ISSUE THREAD

**Issue by akshayysharma** [DPrinceKumar/HactoberFest-2020-4#20]
I am getting this Error: 
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

Could you please do the needful, please 👍

**Comment by DPrinceKumar** [comment]
Share screenshot please

**Comment by DPrinceKumar** [comment]
This repository fullfil all criterion as described by hactoberfest 2020
